services:
  s2-admin:
    image: dpage/pgadmin4:latest
    container_name: 68-s2-admin
    ports:
      - ${PGADMIN_PORT1}:443
      - ${PGADMIN_PORT2}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      
    